export const PREV               = "PREV"
export const NEXT               = "NEXT"
export const GET_ALL_PRODUCTS   = "GET_ALL_PRODUCTS"
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES"
export const APPLY_FILTERS      = "APPLY_FILTERS"